BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "pages_account" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "balance" integer NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
COMMIT;